<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>DAA PROJECT</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<link rel="stylesheet" type="text/css" href="header.css" media="all" />

<script language="javascript" type="text/javascript" src="jquery.js"></script>

<style>
.code
{
	white-space:break-word;
	width:500px;
	height:100px;
	background-color:#F0F0F0;
	overflow:auto;
}
</style>
</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">

<!-- Layout HEADER END -->	
	
<?php echo $this->layout()->content; ?>

<!-- Layout FOOTER BEGIN-->

<img id="bottom" src="bottom.png" alt="">
	
    
	</body>
</html>