<?php

function generateNameRowsFromQue($que)
{
	$locs = $que->loc;
	$ret = '';
	
	foreach($locs as $q)
	{
		$task = $q->isBookedBy();
		
		try
		{
			if(!isset($task))
			{
				throw new Exception('Error');
			}
			else
			{
				$task->isOnTime() ? $addClass='' : $addClass = 'late';
				$ret = $ret.'<td class="task_name value '.$addClass.'">'.$task->name().'</td>
		';
			}
		} 
		catch(Exception $e)
		{
			$ret = $ret.'<td class="task_name value">&nbsp;</td>
		';
		}
	}
	
	return $ret;
}

function generateDRowsFromQue($que)
{
	$locs = $que->loc;
	$ret = '';
	foreach($locs as $q)
	{
		$task = $q->isBookedBy();
		try
		{

			if(!isset($task))
			{
				throw new Exception('Error');
			}
			else
			{
				$task->isOnTime() ? $addClass='' : $addClass = 'late';
				$ret = $ret.'<td class="task_d value '.$addClass.'">'.$task->d().'</td>
		';
			}
		} 
		catch(Exception $e)
		{
			$ret = $ret.'<td class="task_d value">&nbsp;</td>
		';
		}
	}
	
	return $ret;
}

function generateWRowsFromQue($que)
{
	$locs = $que->loc;
	$ret = '';
	foreach($locs as $q)
	{
		$task = $q->isBookedBy();
		try
		{
			if(!isset($task))
			{
				throw new Exception('Error');
			}
			else
			{
				$task->isOnTime() ? $addClass='' : $addClass = 'late';
				$ret = $ret.'<td class="task_w value '.$addClass.'">'.$task->w().'</td>
		';
			}
		} 
		catch(Exception $e)
		{
			$ret = $ret.'<td class="task_w value">&nbsp;</td>
		';
		}
	}
	
	return $ret;
}

function generateNameRowsFromTasks($tasks)
{
	$ret = '';
	foreach($tasks as $task)
	{	
		$task->isOnTime() ? $addClass='' : $addClass = 'late';
		$ret = $ret.'<td class="task_name value '.$addClass.'">'.$task->name().'</td>
		';
	}
	
	return $ret;
}

function generateDRowsFromTasks($tasks)
{
	
	$ret = '';
	foreach($tasks as $task)
	{	
		$task->isOnTime() ? $addClass='' : $addClass = 'late';
		$ret = $ret.'<td class="task_d value '.$addClass.'">'.$task->d().'</td>
		';
	}
	
	return $ret;
}

function generateWRowsFromTasks($tasks)
{
	
	$ret = '';
	foreach($tasks as $task)
	{	
		$task->isOnTime() ? $addClass='' : $addClass = 'late';
		$ret = $ret.'<td class="task_w value '.$addClass.'">'.$task->w().'</td>
		';
	}
	
	return $ret;
}

$onTimeQueNames = generateNameRowsFromQue($this->onTimeQue,true,false);
$onTimeQueDs = generateDRowsFromQue($this->onTimeQue,true,false);
$onTimeQueWs = generateWRowsFromQue($this->onTimeQue,true,false);

$pendingTasksNames = generateNameRowsFromTasks($this->pendingTasks,false);
$pendingTasksDs = generateDRowsFromTasks($this->pendingTasks,false);
$pendingTasksWs = generateWRowsFromTasks($this->pendingTasks,false);

$pendingTasksSortedNames = generateNameRowsFromTasks($this->pendingTasksSorted,false);
$pendingTasksSortedDs = generateDRowsFromTasks($this->pendingTasksSorted,false);
$pendingTasksSortedWs = generateWRowsFromTasks($this->pendingTasksSorted,false);

$finalQueNames = generateNameRowsFromQue($this->finalQue);
$finalQueDs = generateDRowsFromQue($this->finalQue);
$finalQueWs = generateWRowsFromQue($this->finalQue);

?>

    <link rel="stylesheet" type="text/css" href="generateQue.css" media="all" />
    
	<div id="form_container">
    
		<form id="form_post_submit" class="appnitro" method="post" action="index">
			<div class="form_description">
			
                <table class="header_separator">
                    <tr>
                        <td class="header_separator"><h2 id="heading" style="background-color: #E6E6E6;" contenteditable="true" class="header">Final Schedule</h2></td>
                        <td class="header_separator submit" style="text-align:center;"><input type="image" alt="Schedule" src="submit.jpg"/></td>
                    </tr>
                </table>
				
			<br />
				
			<p>Task Scheduling Using Greedy Algorithm</p>
			
			</div>

			<pre><span class="task_heading">Que Size	...	<?php echo $this->qSize; ?></span><br /><span class="task_heading">No. Of Tasks	...	<?php echo $this->tSize; ?></span></pre>
            
			
            <span class="task_heading">Que With On Time Tasks</span>	
			<pre>
            <table class="task" id="task_table_unsorted" width="100%" border="0">
            	<tr>
                	<td class="task_name label">Name	|</td>
                    <?php echo $onTimeQueNames; ?>
                </tr>
                <tr>
                	<td class="task_d label">Deadline|</td>
                    <?php echo $onTimeQueDs; ?>
                </tr>
                <tr>
                	<td class="task_w label">Weight	|</td>
                    <?php echo $onTimeQueWs; ?>
                </tr>
            </table>
            </pre>

            <span class="task_heading">List Of Pending Tasks</span>
            <pre>
            <table class="task" id="task_table_ssorted" width="100%" border="0">
            	<tr>
                	<td class="task_name label">Name	|</td>
                    <?php echo $pendingTasksNames; ?>
                </tr>
                <tr>
                	<td class="task_d label">Deadline|</td>
                    <?php echo $pendingTasksDs; ?>
                </tr>
                <tr>
                	<td class="task_w label">Weight	|</td>
                    <?php echo $pendingTasksWs; ?>
                </tr>
            </table>
            </pre>
            
            <span class="task_heading">List Of Pending Tasks Ordered By Ascending Deadline Time</span>
            <pre>
            <table class="task" id="task_table_ssorted" width="100%" border="0">
            	<tr>
                	<td class="task_name label">Name	|</td>
                    <?php echo $pendingTasksSortedNames; ?>
                </tr>
                <tr>
                	<td class="task_d label">Deadline|</td>
                    <?php echo $pendingTasksSortedDs; ?>
                </tr>
                <tr>
                	<td class="task_w label">Weight	|</td>
                    <?php echo $pendingTasksSortedWs; ?>
                </tr>
            </table>
            </pre>
            
            <span class="task_heading">Final Que</span>
            <pre>
            <table class="task" id="task_table_ssorted" width="100%" border="0">
            	<tr>
                	<td class="task_name label">Name	|</td>
                    <?php echo $finalQueNames; ?>
                </tr>
                <tr>
                	<td class="task_d label">Deadline|</td>
                    <?php echo $finalQueDs; ?>
                </tr>
                <tr>
                	<td class="task_w label">Weight	|</td>
                    <?php echo $finalQueWs; ?>
                </tr>
            </table>
            </pre>
            
           <div class='sum' style="width:100%; text-align:left;"><span class="weight">Total Weight:<br /></span>
		   <?php
				$show='';
				$sum=0;
				foreach($this->pendingTasks as $task)
				{
					$show = $show.$sign.$task->w();
					$sum = $sum+$task->w();
					$sign = ' + ';
				}
				echo $show.' = '.$sum;
		   ?>
		   </div>
		   <div style="width:100%; text-align:right;"><input type="image" alt="Retry" src="generateQue.retry.png" height="30"/></div>
		</form>	 
	</div>
    
    <script language="javascript" type="text/javascript" src="generateTask.js"></script>